spring:
  application:
    name: waitingTime-kiosk
  datasource:
    url: jdbc:h2:tcp://localhost/~/desktop/capstone/kioskData
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
  profiles:
    include: private
  servlet:
    multipart:
      location: C:/Users/Minchang Sung/desktop/capstone/waitingTime-kiosk/src/main/resources/static/img/
      max-file-size: 10MB

logging:
  level:
    org:
      hibernate:
        SQL: debug
        orm:
          jdbc:
            bind: trace
